version: '3.8'

services:
  web:
    build: 
      context: ./flasksocket
      dockerfile: Dockerfile
    # command: uvicorn main:app --host 0.0.0.0
    volumes:
      - ./flasksocket:/app
    ports:
      - 5000:5000
    

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/nginx/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - web
    ports:
      - "80:80"