version: '3.8'

services:
  web:
    build: 
      context: ./flasksocket
      dockerfile: Dockerfile
    # command: uvicorn main:app --host 0.0.0.0
    volumes:
      - ./flasksocket:/app
    ports: 
      - "5000-5002:5000"
    

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/nginx/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - web
    ports:
      - "80:80"

  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm
  
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    depends_on:
      - redis-overcommit

  